REM This is NUnit Bin folder
set nunitPath=%~dp0\bin\net35
REM This is folder with all the DLL generated by Regression Suite
set localPath=%1%
REM This is the DLL of the project we are running test
set assemblyName=%2%
REM This is full qualified name of the testcase we want to run
set caseName=%3%

REM Output paths for debugging
echo nunitPath: %nunitPath%
echo localPath: %localPath%
echo assemblyName: %assemblyName%
echo caseName: %caseName%

cd %nunitPath%
nunit3-console "%localPath%\%assemblyName%" --test:%caseName% --result:"%localPath%\%caseName%.xml;format=nunit3" --noheader --trace=Off